<?php
/**
 * The MIT License
 * Copyright (c) 2018-2020 Lucas Brucksch (lbrucksch@hammermaps.de)
 * https://www.hammermaps.de | https://www.teamspeak-interface.de/
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

namespace TSI_Client;

interface TSI_Role_Interface {
    const tsi_permissions = [
        "tsi_profile_edit",
        "tsi_profile_icon_package_select",
        "tsi_cache_dedicated_update",
        "tsi_instance_import_icon_data",
        "tsi_instance_import_permission_data",
        "tsi_instance_stats_access",
        "tsi_instance_notes_manage",
        "tsi_virtualserver_stats_access",
        "tsi_virtualserver_template_manage",
        "tsi_virtualserver_template_create",
        "tsi_virtualserver_template_modify",
        "tsi_virtualserver_template_delete",
        "tsi_virtualserver_import_icon_data",
        "tsi_virtualserver_kick",
        "tsi_virtualserver_chat",
        "tsi_virtualserver_chat_clear",
        "tsi_virtualserver_reset",
        "tsi_virtualserver_start",
        "tsi_virtualserver_stop",
        "tsi_virtualserver_modify_autostart",
        "tsi_virtualserver_delete",
        "tsi_virtualserver_channel_list_reset",
        "tsi_virtualserver_channel_chat",
        "tsi_virtualserver_channel_kick",
        "tsi_virtualserver_channel_chat_clear",
        "tsi_virtualserver_create",
        "tsi_virtualserver_create_from_template",
        "tsi_virtualserver_log_list",
        "tsi_virtualserver_log_create",
        "tsi_virtualserver_complaints_list",
        "tsi_virtualserver_complaints_delete",
        "tsi_virtualserver_complaints_create",
        "tsi_virtualserver_token_list",
        "tsi_virtualserver_token_delete",
        "tsi_virtualserver_token_create",
        "tsi_virtualserver_ban_list",
        "tsi_virtualserver_ban_delete",
        "tsi_virtualserver_ban_create",
        "tsi_virtualserver_snapshot_list",
        "tsi_virtualserver_snapshot_deploy",
        "tsi_virtualserver_snapshot_create",
        "tsi_virtualserver_snapshot_delete",
        "tsi_virtualserver_snapshot_download",
        "tsi_virtualserver_snapshot_import",
        "tsi_virtualserver_hostbanner_upload",
        "tsi_virtualserver_servergroup_delete",
        "tsi_virtualserver_servergroup_client_list",
        "tsi_virtualserver_servergroup_create",
        "tsi_virtualserver_servergroup_permission_list",
        "tsi_virtualserver_servergroup_template_modify",
        "tsi_virtualserver_servergroup_query_modify",
        "tsi_virtualserver_channelgroup_delete",
        "tsi_virtualserver_channelgroup_client_list",
        "tsi_virtualserver_channelgroup_create",
        "tsi_virtualserver_channelgroup_permission_list",
        "tsi_virtualserver_channelgroup_template_modify",
        "tsi_virtualserver_client_poke",
        "tsi_virtualserver_client_delete",
        "tsi_virtualserver_client_permission_list",
        "tsi_virtualserver_client_add_servergroups",
        "tsi_virtualserver_client_remove_servergroups",
        "tsi_virtualserver_client_modify_channelgroup",
        "tsi_virtualserver_client_private_chat",
        "tsi_virtualserver_client_private_chat_clear",
        "tsi_virtualserver_channel_delete",
        "tsi_virtualserver_channel_create",
        "tsi_virtualserver_files_download",
        "tsi_virtualserver_files_upload",
        "tsi_virtualserver_files_delete",
        "tsi_virtualserver_files_move",
        "tsi_virtualserver_bot_start",
        "tsi_virtualserver_bot_stop",
        "tsi_virtualserver_bot_log_view",
        "tsi_virtualserver_bot_start_modify",
        "tsi_virtualserver_bot_performance_modify",
        "tsi_virtualserver_bot_channel_status_modify",
        "tsi_virtualserver_bot_option_automatic_welcome",
        "tsi_virtualserver_bot_option_command_line",
        "tsi_virtualserver_bot_option_away_from_keyboard",
        "tsi_virtualserver_bot_option_forced_arrest",
        "tsi_virtualserver_bot_option_auto_kick",
        "tsi_virtualserver_bot_option_forced_freezing",
        "tsi_virtualserver_bot_option_protect_servergroups",
        "tsi_virtualserver_bot_option_protect_channelgroups",
        "tsi_virtualserver_music_bot_create",
        "tsi_virtualserver_music_bot_delete",
        "tsi_virtualserver_music_bot_queue_add",
        "tsi_virtualserver_music_bot_action",
        "tsi_virtualserver_music_bot_queue_rem",
        "tsi_virtualserver_music_bot_player"
    ];

    const tsi_permissions_desc = [
        "tsi_profile_edit" => "The user can edit his profile",
        "tsi_profile_icon_package_select" => "The user can set style packages himself",
        "tsi_cache_dedicated_update" => "User can independently update his cache (only with dedicated caching)",
        "tsi_instance_import_icon_data" => "User can import / update icons of the whole instance",
        "tsi_instance_import_permission_data" => "User can import / update the instance rights",
        "tsi_instance_stats_access" => "User has access to statistics of assigned instances",
        "tsi_instance_notes_manage" => "User can create and manage notes for assigned virutal servers",
        "tsi_virtualserver_stats_access" => "User has access to statistics of assigned virtual servers",
        "tsi_virtualserver_template_manage" => "User can manage own templates for virtual servers",
        "tsi_virtualserver_template_create" => "User can create own templates for virtual servers",
        "tsi_virtualserver_template_modify" => "User can edit own templates for virtual servers",
        "tsi_virtualserver_template_delete" => "User can delete own templates for virtual servers",
        "tsi_virtualserver_import_icon_data" => "User can import / update icons of individual servers",
        "tsi_virtualserver_kick" => "User can kick clients from assigned servers",
        "tsi_virtualserver_chat" => "User can use server chat",
        "tsi_virtualserver_chat_clear" => "User can delete his own server chat history",
        "tsi_virtualserver_reset" => "User can reset assigned servers",
        "tsi_virtualserver_start" => "User can start assigned servers",
        "tsi_virtualserver_stop" => "User can stop assigned servers",
        "tsi_virtualserver_modify_autostart" => "User can modify the autostart settings of assigned servers",
        "tsi_virtualserver_delete" => "User can remove assigned servers",
        "tsi_virtualserver_channel_list_reset" => "User can reset the channel list of assigned servers",
        "tsi_virtualserver_channel_chat" => "User can use channel chat",
        "tsi_virtualserver_channel_kick" => "User can kick clients from channel on assigned servers",
        "tsi_virtualserver_channel_chat_clear" => "User can delete his own channel chat history",
        "tsi_virtualserver_create" => "User can create new virtual servers",
        "tsi_virtualserver_create_from_template" => "User can create new virual servers from template",
        "tsi_virtualserver_log_list" => "User can view the logs of assigned servers",
        "tsi_virtualserver_log_create" => "User can create logs for assigned servers",
        "tsi_virtualserver_complaints_list" => "User can view the complaints of assigned servers",
        "tsi_virtualserver_complaints_delete" => "User can remove complaints from assigned servers",
        "tsi_virtualserver_complaints_create" => "User can create complaints on assigned servers",
        "tsi_virtualserver_token_list" => "User can see the authorization keys of assigned servers",
        "tsi_virtualserver_token_delete" => "User can remove permission keys from assigned servers",
        "tsi_virtualserver_token_create" => "User can create authorization keys for assigned servers",
        "tsi_virtualserver_ban_list" => "User can view the ban lists of assigned servers",
        "tsi_virtualserver_ban_delete" => "User can remove relocation of assigned servers",
        "tsi_virtualserver_ban_create" => "User can create bans on assigned servers",
        "tsi_virtualserver_snapshot_list" => "User can see snapshots of assigned servers",
        "tsi_virtualserver_snapshot_deploy" => "User can apply snapshots of assigned servers",
        "tsi_virtualserver_snapshot_create" => "User can create Snaphsots for assigned servers",
        "tsi_virtualserver_snapshot_delete" => "User can remove snapshots of assigned servers",
        "tsi_virtualserver_snapshot_download" => "User can download snapshots of assigned servers",
        "tsi_virtualserver_snapshot_import" => "User can import snapshots to assigned servers",
        "tsi_virtualserver_hostbanner_upload" => "User can upload and change a host banner on assigned servers",
        "tsi_virtualserver_servergroup_delete" => "User can remove server groups of assigned servers",
        "tsi_virtualserver_servergroup_client_list" => "User can view the server group assignments of assigned servers",
        "tsi_virtualserver_servergroup_create" => "User can create server groups for assigned servers",
        "tsi_virtualserver_servergroup_permission_list" => "User has access to the server group rights Overview of assigned servers",
        "tsi_virtualserver_servergroup_template_modify" => "User can edit, delete, and create template server groups for assigned servers",
        "tsi_virtualserver_servergroup_query_modify" => "User can edit, delete, and create query server groups for assigned servers",
        "tsi_virtualserver_channelgroup_delete" => "User can create channel groups for assigned servers",
        "tsi_virtualserver_channelgroup_client_list" => "User can view the channel group assignments of assigned servers",
        "tsi_virtualserver_channelgroup_create" => "User can remove channel groups of assigned servers",
        "tsi_virtualserver_channelgroup_permission_list" => "User has access to the Channel Group Rights Overview of assigned servers",
        "tsi_virtualserver_channelgroup_template_modify" => "User can edit, delete and create template channel groups for assigned servers",
        "tsi_virtualserver_client_poke" => "User can poke clients on assigned servers",
        "tsi_virtualserver_client_delete" => "User can delete clients stored in the database for assigned servers",
        "tsi_virtualserver_client_permission_list" => "User can edit the rights of the clients stored in the database for assigned servers",
        "tsi_virtualserver_client_add_servergroups" => "Users can assign all server groups to clients for assigned servers",
        "tsi_virtualserver_client_remove_servergroups" => "User can remove clients for assigned servers from all server groups",
        "tsi_virtualserver_client_modify_channelgroup" => "User can modify the Channel Group of clients on assigned servers",
        "tsi_virtualserver_client_private_chat" => "User can use private client chat",
        "tsi_virtualserver_client_private_chat_clear" => "User can delete his own private chat history",
        "tsi_virtualserver_channel_delete" => "User can remove channels from assigned servers",
        "tsi_virtualserver_channel_create" => "User can create channels on assigned servers",
        "tsi_virtualserver_files_download" => "User can download files",
        "tsi_virtualserver_files_upload" => "User can upload files",
        "tsi_virtualserver_files_delete" => "User can delete files",
        "tsi_virtualserver_files_move" => "User can move files",
        "tsi_virtualserver_bot_start" => "User can start simple bots on assigned servers",
        "tsi_virtualserver_bot_stop" => "User can stop simple bots on assigned servers",
        "tsi_virtualserver_bot_log_view" => "The user has access to the error logs of simple bots",
        "tsi_virtualserver_bot_start_modify" => "User has access to the startup options of simple bots",
        "tsi_virtualserver_bot_performance_modify" => "User has access to the performance options of simple bots",
        "tsi_virtualserver_bot_channel_status_modify" => "User can change the channel status from simple bots to assigned servers",
        "tsi_virtualserver_bot_option_automatic_welcome" => "User has access to the 'automatic welcoming' configuration options of the simple bot",
        "tsi_virtualserver_bot_option_command_line" => "User has access to the 'command line' configuration options of the simple bot",
        "tsi_virtualserver_bot_option_away_from_keyboard" => "User has access to the 'away from keyboard' configuration options of the simple bot",
        "tsi_virtualserver_bot_option_forced_arrest" => "User has access to the 'forced arrest' configuration options of the simple bot",
        "tsi_virtualserver_bot_option_auto_kick" => "User has access to the 'automatic kick' configuration options of the simple bot",
        "tsi_virtualserver_bot_option_forced_freezing" => "User has access to the 'forced freezing' configuration options of the simple bot",
        "tsi_virtualserver_bot_option_protect_servergroups" => "User can protect any servergroup using simple bots on assigned servers",
        "tsi_virtualserver_bot_option_protect_channelgroups" => "User can protect any channelgroup using simple bots on assigned servers",
        "tsi_virtualserver_music_bot_create" => "User can create music bots (TeaSpeak only)",
        "tsi_virtualserver_music_bot_delete" => "User can delete music bots (TeaSpeak only)",
        "tsi_virtualserver_music_bot_queue_add" => "User can add songs to the queue (TeaSpeak only)",
        "tsi_virtualserver_music_bot_action" => "User can stop, pause and play songs (TeaSpeak only)",
        "tsi_virtualserver_music_bot_queue_rem" => "User can remove songs from the queue",
        "tsi_virtualserver_music_bot_player" => "User has access to the Music Bot Player"
    ];

    const virtualserver_modify_desc = array(
        "virtualserver_name" => "User can edit the name of assigned servers",
        "virtualserver_icon_id" => "User can edit the icon of assigned servers",
        "virtualserver_port" => "User can edit the port number of assigned servers",
        "virtualserver_welcomemessage" => "User can edit the welcomemessage of assigned server",
        "virtualserver_password" => "User can edit the password of assigned servers",
        "virtualserver_maxclients" => "User can change the number of max assigned server users",
        "virtualserver_reserved_slots" => "User can reserve slots for assigned servers",
        "virtualserver_weblist_enabled" => "User can enter assigned servers in the web list",
        "virtualserver_hostmessage" => "User can edit the hostmessage of assigned servers",
        "virtualserver_hostbanner_url" => "User can edit the hostbanner url of assigned servers",
        "virtualserver_hostbanner_gfx_url" => "User can edit the banner graphic of the assigned servers",
        "virtualserver_hostbanner_gfx_intervall" => "User can change the banner graphics interval on assigned servers",
        "virtualserver_hostbutton_tooltip" => "User can edit the hostbutton tooltip of assigned servers",
        "virtualserver_hostbutton_gfx_url" => "User can edit the hostbutton graphic of the assigned servers",
        "virtualserver_hostbutton_url" => "User can edit the hostbutton url of assigned servers",
        "virtualserver_max_download_total_bandwith" => "User can change the download bandwidth on assigned servers",
        "virtualserver_download_quota" => "User can change the limit on downloads on assigned servers",
        "virtualserver_max_upload_total_bandwith" => "User can change the upload bandwidth on assigned servers",
        "virtualserver_upload_quota" => "User can change the limit on uploads on assigned servers",
        "virtualserver_anti_flood_options" => "User modify edit the anti-flood options of assigned servers",
        "virtualserver_security_options" => "User modify edit the security options of assigned servers",
        "virtualserver_standard_groups_options" => "User can modify the standard groups of assigned servers",
        "virtualserver_compainment_options" => "User can modify complainment options of assigned servers",
        "virtualserver_other_options" => "User can modify other options of assigned servers",
        "virtualserver_protocol_options" => "User can modify protocol options of assigned servers"
    );

    const virtualserver_channel_modify = array(
        "channel_name",
        "channel_icon_id",
        "channel_password",
        "channel_topic",
        "channel_description",
        "channel_type_options",
        "channel_moderation_options",
        "channel_audio_options",
        "channel_normal_needed_power_options",
        "channel_filetransfer_needed_power_options",
        "channel_other_options",
        "channel_max_clients_options",
        "channel_max_client_tree_options"
    );

    const virtualserver_channel_modify_desc = array(
        "channel_name" => "User can edit the channel names of assigned servers",
        "channel_icon_id" => "User can edit the channel icons of assigned servers",
        "channel_password" => "User can edit the channel passwords of assigned servers",
        "channel_topic" => "User can edit the channel topics of assigned servers",
        "channel_description" => "User can edit the channel descriptions of assigned servers",
        "channel_type_options" => "User can edit the channel types of assigned servers",
        "channel_moderation_options" => "User can edit the channel moderation options of assigned servers",
        "channel_audio_options" => "User can edit the channel audio options of assigned servers",
        "channel_normal_needed_power_options" => "User can edit the channel normal needed power options of assigned servers",
        "channel_filetransfer_needed_power_options" => "User can edit the channel filetransfer needed power options of assigned servers",
        "channel_other_options" => "User can edit the other channel options of assigned servers",
        "channel_max_clients_options" => "User can edit the channel max client options of assigned servers",
        "channel_max_client_tree_options" => "User can edit the channel client tree options of assigned servers"
    );

    const virtualserver_permissions = array(
        "serverinstance" => array(
            "b_serverinstance_help_view",
            "b_serverinstance_version_view",
            "b_serverinstance_info_view",
            "b_serverinstance_virtualserver_list",
            "b_serverinstance_binding_list",
            "b_serverinstance_permission_list",
            "b_serverinstance_permission_find",
            "b_serverinstance_textmessage_send",
            "b_serverinstance_log_view",
            "b_serverinstance_log_add",
            "b_serverinstance_stop",
            "b_serverinstance_modify_settings",
            "b_serverinstance_modify_querygroup",
            "b_serverinstance_modify_templates"
        ),
        "serverquery" => array(
            "b_serverquery_login"
        ),
        "virtualserver" => array(
            "b_virtualserver_create",
            "b_virtualserver_delete",
            "b_virtualserver_start_any",
            "b_virtualserver_stop_any",
            "b_virtualserver_change_machine_id",
            "b_virtualserver_change_template",
            "b_virtualserver_select",
            "b_virtualserver_info_view",
            "b_virtualserver_connectioninfo_view",
            "b_virtualserver_channel_list",
            "b_virtualserver_channel_search",
            "b_virtualserver_client_list",
            "b_virtualserver_client_search",
            "b_virtualserver_client_dblist",
            "b_virtualserver_client_dbsearch",
            "b_virtualserver_client_dbinfo",
            "b_virtualserver_permission_find",
            "b_virtualserver_custom_search",
            "b_virtualserver_start",
            "b_virtualserver_stop",
            "b_virtualserver_token_list",
            "b_virtualserver_token_add",
            "b_virtualserver_token_use",
            "b_virtualserver_token_delete",
            "b_virtualserver_log_view",
            "b_virtualserver_log_add",
            "b_virtualserver_join_ignore_password",
            "b_virtualserver_notify_register",
            "b_virtualserver_notify_unregister",
            "b_virtualserver_snapshot_create",
            "b_virtualserver_snapshot_deploy",
            "b_virtualserver_permission_reset",
            "b_virtualserver_modify_name",
            "b_virtualserver_modify_welcomemessage",
            "b_virtualserver_modify_maxclients",
            "b_virtualserver_modify_reserved_slots",
            "b_virtualserver_modify_password",
            "b_virtualserver_modify_default_servergroup",
            "b_virtualserver_modify_default_channelgroup",
            "b_virtualserver_modify_default_channeladmingroup",
            "b_virtualserver_modify_channel_forced_silence",
            "b_virtualserver_modify_complain",
            "b_virtualserver_modify_antiflood",
            "b_virtualserver_modify_ft_settings",
            "b_virtualserver_modify_ft_quotas",
            "b_virtualserver_modify_hostmessage",
            "b_virtualserver_modify_hostbanner",
            "b_virtualserver_modify_hostbutton",
            "b_virtualserver_modify_port",
            "b_virtualserver_modify_autostart",
            "b_virtualserver_modify_needed_identity_security_level",
            "b_virtualserver_modify_priority_speaker_dimm_modificator",
            "b_virtualserver_modify_log_settings",
            "b_virtualserver_modify_min_client_version",
            "b_virtualserver_modify_icon_id",
            "b_virtualserver_modify_weblist",
            "b_virtualserver_modify_codec_encryption_mode",
            "b_virtualserver_modify_temporary_passwords",
            "b_virtualserver_modify_temporary_passwords_own",
            "b_virtualserver_modify_channel_temp_delete_delay_default",
            "i_icon_id",
            "i_max_icon_filesize",
            "b_icon_manage"
        ),
        "channel" => array(
            "i_channel_min_depth",
            "i_channel_max_depth",
            "b_channel_group_inheritance_end",
            "i_channel_permission_modify_power",
            "i_channel_needed_permission_modify_power",
            "b_channel_info_view",
            "b_channel_create_child",
            "b_channel_create_permanent",
            "b_channel_create_semi_permanent",
            "b_channel_create_temporary",
            "b_channel_create_private",
            "b_channel_create_with_topic",
            "b_channel_create_with_description",
            "b_channel_create_with_password",
            "b_channel_create_modify_with_codec_speex8",
            "b_channel_create_modify_with_codec_speex16",
            "b_channel_create_modify_with_codec_speex32",
            "b_channel_create_modify_with_codec_celtmono48",
            "b_channel_create_modify_with_codec_opusvoice",
            "b_channel_create_modify_with_codec_opusmusic",
            "i_channel_create_modify_with_codec_maxquality",
            "i_channel_create_modify_with_codec_latency_factor_min",
            "b_channel_create_with_maxclients",
            "b_channel_create_with_maxfamilyclients",
            "b_channel_create_with_sortorder",
            "b_channel_create_with_default",
            "b_channel_create_with_needed_talk_power",
            "b_channel_create_modify_with_force_password",
            "i_channel_create_modify_with_temp_delete_delay",
            "b_channel_modify_parent",
            "b_channel_modify_make_default",
            "b_channel_modify_make_permanent",
            "b_channel_modify_make_semi_permanent",
            "b_channel_modify_make_temporary",
            "b_channel_modify_name",
            "b_channel_modify_topic",
            "b_channel_modify_description",
            "b_channel_modify_password",
            "b_channel_modify_codec",
            "b_channel_modify_codec_quality",
            "b_channel_modify_codec_latency_factor",
            "b_channel_modify_maxclients",
            "b_channel_modify_maxfamilyclients",
            "b_channel_modify_sortorder",
            "b_channel_modify_needed_talk_power",
            "i_channel_modify_power",
            "i_channel_needed_modify_power",
            "b_channel_modify_make_codec_encrypted",
            "b_channel_modify_temp_delete_delay",
            "b_channel_delete_permanent",
            "b_channel_delete_semi_permanent",
            "b_channel_delete_temporary",
            "b_channel_delete_flag_force",
            "i_channel_delete_power",
            "i_channel_needed_delete_power",
            "b_channel_join_permanent",
            "b_channel_join_semi_permanent",
            "b_channel_join_temporary",
            "b_channel_join_ignore_password",
            "b_channel_join_ignore_maxclients",
            "i_channel_join_power",
            "i_channel_needed_join_power",
            "i_channel_subscribe_power",
            "i_channel_needed_subscribe_power",
            "i_channel_description_view_power",
            "i_channel_needed_description_view_power",
            "b_virtualserver_channel_permission_list",
            "b_virtualserver_channelclient_permission_list"
        ),
        "group" => array(
            "b_group_is_permanent",
            "i_group_auto_update_type",
            "i_group_auto_update_max_value",
            "i_group_sort_id",
            "i_group_show_name_in_tree",
            "b_virtualserver_servergroup_list",
            "b_virtualserver_servergroup_permission_list",
            "b_virtualserver_servergroup_client_list",
            "b_virtualserver_channelgroup_list",
            "b_virtualserver_channelgroup_permission_list",
            "b_virtualserver_channelgroup_client_list",
            "b_virtualserver_servergroup_create",
            "b_virtualserver_channelgroup_create",
            "i_group_modify_power",
            "i_group_needed_modify_power",
            "i_group_member_add_power",
            "i_group_needed_member_add_power",
            "i_group_member_remove_power",
            "i_group_needed_member_remove_power",
            "b_virtualserver_servergroup_delete",
            "b_virtualserver_channelgroup_delete",
            "i_permission_modify_power",
            "b_permission_modify_power_ignore"
        ),
        "client" => array(
            "b_virtualserver_client_permission_list",
            "i_client_permission_modify_power",
            "i_client_needed_permission_modify_power",
            "i_client_max_clones_uid",
            "i_client_max_idletime",
            "i_client_max_avatar_filesize",
            "i_client_max_channel_subscriptions",
            "b_client_is_priority_speaker",
            "b_client_force_push_to_talk",
            "b_client_ignore_bans",
            "b_client_ignore_antiflood",
            "b_client_issue_client_query_command",
            "b_client_use_reserved_slot",
            "b_client_use_channel_commander",
            "b_client_request_talker",
            "b_client_avatar_delete_other",
            "b_client_is_sticky",
            "b_client_ignore_sticky",
            "b_client_info_view",
            "b_client_permissionoverview_view",
            "b_client_permissionoverview_own",
            "b_client_remoteaddress_view",
            "i_client_serverquery_view_power",
            "i_client_needed_serverquery_view_power",
            "b_client_custom_info_view",
            "i_client_kick_from_server_power",
            "i_client_needed_kick_from_server_power",
            "i_client_kick_from_channel_power",
            "i_client_needed_kick_from_channel_power",
            "i_client_ban_power",
            "i_client_needed_ban_power",
            "i_client_move_power",
            "i_client_needed_move_power",
            "i_client_complain_power",
            "i_client_needed_complain_power",
            "b_client_complain_list",
            "b_client_complain_delete_own",
            "b_client_complain_delete",
            "b_client_ban_list",
            "b_client_ban_create",
            "b_client_ban_delete_own",
            "b_client_ban_delete",
            "i_client_ban_max_bantime",
            "i_client_private_textmessage_power",
            "i_client_needed_private_textmessage_power",
            "b_client_server_textmessage_send",
            "b_client_channel_textmessage_send",
            "b_client_offline_textmessage_send",
            "i_client_talk_power",
            "i_client_needed_talk_power",
            "i_client_poke_power",
            "i_client_needed_poke_power",
            "b_client_set_flag_talker",
            "i_client_whisper_power",
            "i_client_needed_whisper_power",
            "b_client_modify_description",
            "b_client_modify_own_description",
            "b_client_modify_dbproperties",
            "b_client_delete_dbproperties",
            "b_client_create_modify_serverquery_login",
            "b_client_skip_channelgroup_permissions",
        ),
        "filetransfer" => array(
            "b_ft_ignore_password",
            "b_ft_transfer_list",
            "i_ft_file_upload_power",
            "i_ft_needed_file_upload_power",
            "i_ft_file_download_power",
            "i_ft_needed_file_download_power",
            "i_ft_file_delete_power",
            "i_ft_needed_file_delete_power",
            "i_ft_file_rename_power",
            "i_ft_needed_file_rename_power",
            "i_ft_file_browse_power",
            "i_ft_needed_file_browse_power",
            "i_ft_directory_create_power",
            "i_ft_needed_directory_create_power",
            "i_ft_quota_mb_download_per_client",
            "i_ft_quota_mb_upload_per_client"
        )
    );

    //SETTER
    public function setID(int $id);
    public function setName(string $name);
    public function setLevel(int $level);
    public function setIcon(string $icon);
    public function setPermission(string $permission,bool $granted);
    public function setPermissions(array $permissions);
    public function setModify(string $permission,bool $granted);
    public function setModifys(array $modify);
    public function setChannelModify(string $permission,bool $granted);
    public function setChannelModifys(array $channel_modify);
    public function setTSIPermission(string $permission,bool $granted);
    public function setTSIPermissions(array $tsi_permissions);

    //GETTER
    public function getID();
    public function getName();
    public function getLevel();
    public function getIcon();
    public function getPermissions();
    public function getPermission(string $permission);
    public function getPermissionsList();
    public function getModifys();
    public function getModify(string $permission);
    public function getModifyList();
    public function getChannelModifys();
    public function getChannelModify(string $permission);
    public function getChannelModifyList();
    public function getTSIPermissions();
    public function getTSIPermission(string $permission);
    public function getTSIPermissionsList();
}