.TH "src/models Directory Reference" 3 "Tue Oct 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTSI_Instance\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_Instance_Interface\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_Properties\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_Properties_Interface\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_Role\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_Role_Interface\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_User\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_User_Interface\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_VServer\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_VServer_Interface\&.php\fP"
.br
.in -1c
