.TH "src Directory Reference" 3 "Tue Oct 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmodels\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTSI_Client\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_Client_Base\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_Client_Base_Interface\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_Client_Interface\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_MultiClient\&.php\fP"
.br
.ti -1c
.RI "file \fBTSI_MultiClient_Interface\&.php\fP"
.br
.in -1c
