.TH "TSI_VServer" 3 "Tue Oct 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_VServer
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
TSI-Virtual-Server: v1\&.0\&.61 Class \fBTSI_VServer\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for TeamSpeak Interface Client from the source code\&.
