.TH "src/models/TSI_Properties_Interface.php" 3 "Tue Oct 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/models/TSI_Properties_Interface.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBTSI_Properties_Interface\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTSI_Client\\Models\fP"
.br
.ti -1c
.RI " \fBTSI_Client\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TeamSpeak Interface Client from the source code\&.
