.TH "TSI_Instance_Interface" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_Instance_Interface
.SH SYNOPSIS
.br
.PP
.PP
Basisklasse für \fBTSI_Instance\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBsetID\fP (int $user_id)"
.br
.ti -1c
.RI "\fBsetIP\fP (string $server_ip)"
.br
.ti -1c
.RI "\fBsetQueryPort\fP (int $query_port)"
.br
.ti -1c
.RI "\fBsetServerAdmin\fP (string $serveradmin)"
.br
.ti -1c
.RI "\fBsetLastPermImport\fP (string $last_perm_import)"
.br
.ti -1c
.RI "\fBgetID\fP ()"
.br
.ti -1c
.RI "\fBgetIP\fP ()"
.br
.ti -1c
.RI "\fBgetQueryPort\fP ()"
.br
.ti -1c
.RI "\fBgetServerAdmin\fP ()"
.br
.ti -1c
.RI "\fBgetLastPermImport\fP ()"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 32 der Datei TSI_Instance_Interface\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
