.TH "TSI_MultiClient_Interface" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_MultiClient_Interface
.SH SYNOPSIS
.br
.PP
.PP
Abgeleitet von \fBTSI_Client_Interface\fP\&.
.PP
Basisklasse für \fBTSI_MultiClient\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBgetTSIUser\fP (int $user_id)"
.br
.in -1c
.SS "Weitere Geerbte Elemente"
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 34 der Datei TSI_MultiClient_Interface\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
