.TH "TSI_Properties_Interface" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_Properties_Interface
.SH SYNOPSIS
.br
.PP
.PP
Basisklasse für \fBTSI_Properties\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBsetName\fP (string $name)"
.br
.ti -1c
.RI "\fBsetPort\fP (int $port)"
.br
.ti -1c
.RI "\fBsetPassword\fP (string $password)"
.br
.ti -1c
.RI "\fBsetMaxClients\fP (int $clients)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetPort\fP ()"
.br
.ti -1c
.RI "\fBgetMaxClients\fP ()"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 32 der Datei TSI_Properties_Interface\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
