.TH "TSI_MultiClient" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_MultiClient
.SH SYNOPSIS
.br
.PP
.PP
Abgeleitet von \fBTSI_Client\fP und \fBTSI_MultiClient_Interface\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBTSI_Client\fP $client)"
.br
.ti -1c
.RI "\fB__destruct\fP ()"
.br
.ti -1c
.RI "\fBgetTSIUser\fP (int $user_id)"
.br
.in -1c
.SS "Weitere Geerbte Elemente"
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 35 der Datei TSI_MultiClient\&.php\&.
.SH "Beschreibung der Konstruktoren und Destruktoren"
.PP 
.SS "__construct (\fBTSI_Client\fP $client)"
\fBTSI_MultiClient\fP constructor\&. 
.PP
\fBParameter:\fP
.RS 4
\fI$client\fP 
.RE
.PP

.PP
Definiert in Zeile 40 der Datei TSI_MultiClient\&.php\&.
.SS "__destruct ()"
\fBTSI_MultiClient\fP deconstruct\&. 
.PP
Definiert in Zeile 74 der Datei TSI_MultiClient\&.php\&.
.SH "Dokumentation der Elementfunktionen"
.PP 
.SS "getTSIUser (int $user_id)"
Give a TSI User Profile with Instance and VServers 
.PP
\fBParameter:\fP
.RS 4
\fI$user_id\fP 
.RE
.PP
\fBRückgabe:\fP
.RS 4
Models|bool 
.RE
.PP
\fBAusnahmebehandlung:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implementiert \fBTSI_MultiClient_Interface\fP\&.
.PP
Definiert in Zeile 84 der Datei TSI_MultiClient\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
