.TH "TSI_Properties" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_Properties
.SH SYNOPSIS
.br
.PP
.PP
Abgeleitet von \fBTSI_Properties_Interface\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBsetName\fP (string $name)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBsetPort\fP (int $port)"
.br
.ti -1c
.RI "\fBgetPort\fP ()"
.br
.ti -1c
.RI "\fBsetPassword\fP (string $password)"
.br
.ti -1c
.RI "\fBsetMaxClients\fP (int $clients)"
.br
.ti -1c
.RI "\fBgetMaxClients\fP ()"
.br
.in -1c
.SS "Datenfelder"

.in +1c
.ti -1c
.RI "\fB$virtualserver_options\fP = []"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 32 der Datei TSI_Properties\&.php\&.
.SH "Dokumentation der Elementfunktionen"
.PP 
.SS "getMaxClients ()"
Get number of max server slots 
.PP
\fBRückgabe:\fP
.RS 4
int 
.RE
.PP

.PP
Implementiert \fBTSI_Properties_Interface\fP\&.
.PP
Definiert in Zeile 90 der Datei TSI_Properties\&.php\&.
.SS "getName ()"
Get server name 
.PP
\fBRückgabe:\fP
.RS 4
string 
.RE
.PP

.PP
Implementiert \fBTSI_Properties_Interface\fP\&.
.PP
Definiert in Zeile 50 der Datei TSI_Properties\&.php\&.
.SS "getPort ()"
Get voice server port 
.PP
\fBRückgabe:\fP
.RS 4
int 
.RE
.PP

.PP
Implementiert \fBTSI_Properties_Interface\fP\&.
.PP
Definiert in Zeile 66 der Datei TSI_Properties\&.php\&.
.SS "setMaxClients (int $clients)"
Set number of max server slots 
.PP
\fBParameter:\fP
.RS 4
\fI$clients\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Properties_Interface\fP\&.
.PP
Definiert in Zeile 82 der Datei TSI_Properties\&.php\&.
.SS "setName (string $name)"
Set server name 
.PP
\fBParameter:\fP
.RS 4
\fI$name\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Properties_Interface\fP\&.
.PP
Definiert in Zeile 42 der Datei TSI_Properties\&.php\&.
.SS "setPassword (string $password)"
Set server password 
.PP
\fBParameter:\fP
.RS 4
\fI$password\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Properties_Interface\fP\&.
.PP
Definiert in Zeile 74 der Datei TSI_Properties\&.php\&.
.SS "setPort (int $port)"
Set voice server port 
.PP
\fBParameter:\fP
.RS 4
\fI$port\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Properties_Interface\fP\&.
.PP
Definiert in Zeile 58 der Datei TSI_Properties\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
