.TH "TSI_User_Interface" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_User_Interface
.SH SYNOPSIS
.br
.PP
.PP
Basisklasse für \fBTSI_User\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBsetUserID\fP (int $user_id)"
.br
.ti -1c
.RI "\fBsetResellerID\fP (int $id)"
.br
.ti -1c
.RI "\fBsetRoleID\fP (int $role_id)"
.br
.ti -1c
.RI "\fBsetUsername\fP (string $username)"
.br
.ti -1c
.RI "\fBsetFirstName\fP (string $first_name)"
.br
.ti -1c
.RI "\fBsetLastName\fP (string $last_name)"
.br
.ti -1c
.RI "\fBsetEmail\fP (string $email)"
.br
.ti -1c
.RI "\fBsetQueryNickname\fP (string $query_name)"
.br
.ti -1c
.RI "\fBsetLanguage\fP (string $lang)"
.br
.ti -1c
.RI "\fBsetFixedVMs\fP (array $vms)"
.br
.ti -1c
.RI "\fBsetMaxSlotsVMs\fP (int $slots)"
.br
.ti -1c
.RI "\fBsetRegDateArray\fP (array $reg_date)"
.br
.ti -1c
.RI "\fBsetActive\fP (bool $active)"
.br
.ti -1c
.RI "\fBsetIcon\fP (string $icon_pkg)"
.br
.ti -1c
.RI "\fBsetInitPassword\fP (string $password)"
.br
.ti -1c
.RI "\fBsetServer\fP (int $instance, int $vserver_id)"
.br
.ti -1c
.RI "\fBgetUserID\fP ()"
.br
.ti -1c
.RI "\fBgetResellerID\fP ()"
.br
.ti -1c
.RI "\fBgetRoleID\fP ()"
.br
.ti -1c
.RI "\fBgetUsername\fP ()"
.br
.ti -1c
.RI "\fBgetFirstName\fP ()"
.br
.ti -1c
.RI "\fBgetLastName\fP ()"
.br
.ti -1c
.RI "\fBgetEmail\fP ()"
.br
.ti -1c
.RI "\fBgetQueryNickname\fP ()"
.br
.ti -1c
.RI "\fBgetLanguage\fP ()"
.br
.ti -1c
.RI "\fBgetFixedVMs\fP ()"
.br
.ti -1c
.RI "\fBgetMaxSlotsVMs\fP ()"
.br
.ti -1c
.RI "\fBgetRegDate\fP ()"
.br
.ti -1c
.RI "\fBgetRegDateTimezone\fP ()"
.br
.ti -1c
.RI "\fBgetRegDateTimezoneType\fP ()"
.br
.ti -1c
.RI "\fBgetActive\fP ()"
.br
.ti -1c
.RI "\fBgetIcon\fP ()"
.br
.ti -1c
.RI "\fBgetServer\fP (int $instance, int $vserver_id)"
.br
.ti -1c
.RI "\fBgetVMsByInstance\fP (int $instance)"
.br
.ti -1c
.RI "\fBgetServersMulti\fP ()"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 32 der Datei TSI_User_Interface\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
