.TH "TSI_Client" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_Client
.SH SYNOPSIS
.br
.PP
.SS "Namensbereiche"

.in +1c
.ti -1c
.RI " \fBModels\fP"
.br
.in -1c
.SS "Datenstrukturen"

.in +1c
.ti -1c
.RI "class \fBTSI_Client\fP"
.br
.ti -1c
.RI "class \fBTSI_Client_Base\fP"
.br
.ti -1c
.RI "interface \fBTSI_Client_Base_Interface\fP"
.br
.ti -1c
.RI "interface \fBTSI_Client_Interface\fP"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Class TSI_Instance 
.PP
Interface TSI_Instance_Interface 
.PP
Class TSI_Properties 
.PP
Interface TSI_Properties_Interface 
.PP
Class TSI_Role 
.PP
Interface TSI_Role_Interface 
.PP
Class TSI_User 
.PP
Interface TSI_User_Interface 
.PP
Class TSI_VServer 
.PP
Interface TSI_VServer_Interface 
.PP
The MIT License Copyright (c) 2018-2020 Lucas Brucksch (lbrucksch@hammermaps.de) https://www.hammermaps.de | https://www.teamspeak-interface.de/
.PP
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
Class \fBTSI_Client\fP
.PP
Class \fBTSI_Client_Base\fP
.PP
Interface \fBTSI_Client_Base_Interface\fP
.PP
Interface \fBTSI_Client_Interface\fP 
.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
