.TH "TSI_VServer_Interface" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_VServer_Interface
.SH SYNOPSIS
.br
.PP
.PP
Basisklasse für \fBTSI_VServer\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBsetInstanceID\fP (int $instance_id)"
.br
.ti -1c
.RI "\fBsetServerID\fP (int $server_id)"
.br
.ti -1c
.RI "\fBsetUID\fP (string $unique_id)"
.br
.ti -1c
.RI "\fBsetServerName\fP (string $name)"
.br
.ti -1c
.RI "\fBsetOnline\fP ($status)"
.br
.ti -1c
.RI "\fBsetPlatform\fP (string $platform)"
.br
.ti -1c
.RI "\fBsetVersion\fP (string $version)"
.br
.ti -1c
.RI "\fBsetMaxClients\fP (int $maxclients)"
.br
.ti -1c
.RI "\fBsetClientsOnline\fP (int $clientsonline)"
.br
.ti -1c
.RI "\fBsetChannelOnline\fP (int $channelsonline)"
.br
.ti -1c
.RI "\fBsetCreatedTime\fP (int $createdtime)"
.br
.ti -1c
.RI "\fBsetUptime\fP (int $uptime)"
.br
.ti -1c
.RI "\fBsetProperties\fP (\fBTSI_Properties\fP $properties)"
.br
.ti -1c
.RI "\fBgetInstanceID\fP ()"
.br
.ti -1c
.RI "\fBgetServerID\fP ()"
.br
.ti -1c
.RI "\fBgetUID\fP ()"
.br
.ti -1c
.RI "\fBgetServerName\fP ()"
.br
.ti -1c
.RI "\fBgetOnline\fP ()"
.br
.ti -1c
.RI "\fBgetPlatform\fP ()"
.br
.ti -1c
.RI "\fBgetVersion\fP ()"
.br
.ti -1c
.RI "\fBgetMaxClients\fP ()"
.br
.ti -1c
.RI "\fBgetClientsOnline\fP ()"
.br
.ti -1c
.RI "\fBgetChannelOnline\fP ()"
.br
.ti -1c
.RI "\fBgetCreatedTime\fP ()"
.br
.ti -1c
.RI "\fBgetUptime\fP ()"
.br
.ti -1c
.RI "\fBgetProperties\fP ()"
.br
.ti -1c
.RI "\fBisTeaSpeak\fP ()"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 32 der Datei TSI_VServer_Interface\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
