.TH "TSI_Role" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_Role
.SH SYNOPSIS
.br
.PP
.PP
Abgeleitet von \fBTSI_Role_Interface\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBsetID\fP (int $id)"
.br
.ti -1c
.RI "\fBgetID\fP ()"
.br
.ti -1c
.RI "\fBsetName\fP (string $name)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBsetLevel\fP (int $level)"
.br
.ti -1c
.RI "\fBgetLevel\fP ()"
.br
.ti -1c
.RI "\fBsetIcon\fP (string $icon)"
.br
.ti -1c
.RI "\fBgetIcon\fP ()"
.br
.ti -1c
.RI "\fBsetPermissions\fP (array $permissions)"
.br
.ti -1c
.RI "\fBsetPermission\fP (string $permission, bool $granted=false)"
.br
.ti -1c
.RI "\fBgetPermission\fP (string $permission)"
.br
.ti -1c
.RI "\fBgetPermissions\fP ()"
.br
.ti -1c
.RI "\fBgetPermissionsList\fP ()"
.br
.ti -1c
.RI "\fBsetModifys\fP (array $modify)"
.br
.ti -1c
.RI "\fBsetModify\fP (string $permission, bool $granted=false)"
.br
.ti -1c
.RI "\fBgetModify\fP (string $permission)"
.br
.ti -1c
.RI "\fBgetModifys\fP ()"
.br
.ti -1c
.RI "\fBgetModifyList\fP ()"
.br
.ti -1c
.RI "\fBsetChannelModifys\fP (array $channel_modify)"
.br
.ti -1c
.RI "\fBsetChannelModify\fP (string $permission, bool $granted=false)"
.br
.ti -1c
.RI "\fBgetChannelModify\fP (string $permission)"
.br
.ti -1c
.RI "\fBgetChannelModifys\fP ()"
.br
.ti -1c
.RI "\fBgetChannelModifyList\fP ()"
.br
.ti -1c
.RI "\fBsetTSIPermission\fP (string $permission, bool $granted=false)"
.br
.ti -1c
.RI "\fBgetTSIPermission\fP (string $permission)"
.br
.ti -1c
.RI "\fBsetTSIPermissions\fP (array $tsi_permissions)"
.br
.ti -1c
.RI "\fBgetTSIPermissions\fP ()"
.br
.ti -1c
.RI "\fBgetTSIPermissionsList\fP ()"
.br
.in -1c
.SS "Weitere Geerbte Elemente"
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 34 der Datei TSI_Role\&.php\&.
.SH "Dokumentation der Elementfunktionen"
.PP 
.SS "getChannelModify (string $permission)"

.PP
\fBParameter:\fP
.RS 4
\fI$permission\fP 
.RE
.PP
\fBRückgabe:\fP
.RS 4
bool 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 342 der Datei TSI_Role\&.php\&.
.SS "getChannelModifyList ()"

.PP
\fBRückgabe:\fP
.RS 4
array 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 374 der Datei TSI_Role\&.php\&.
.SS "getChannelModifys ()"

.PP
\fBRückgabe:\fP
.RS 4
array 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 367 der Datei TSI_Role\&.php\&.
.SS "getIcon ()"

.PP
\fBRückgabe:\fP
.RS 4
string 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 152 der Datei TSI_Role\&.php\&.
.SS "getID ()"

.PP
\fBRückgabe:\fP
.RS 4
int 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 98 der Datei TSI_Role\&.php\&.
.SS "getLevel ()"

.PP
\fBRückgabe:\fP
.RS 4
int 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 138 der Datei TSI_Role\&.php\&.
.SS "getModify (string $permission)"

.PP
\fBParameter:\fP
.RS 4
\fI$permission\fP 
.RE
.PP
\fBRückgabe:\fP
.RS 4
bool 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 271 der Datei TSI_Role\&.php\&.
.SS "getModifyList ()"

.PP
\fBRückgabe:\fP
.RS 4
array 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 303 der Datei TSI_Role\&.php\&.
.SS "getModifys ()"

.PP
\fBRückgabe:\fP
.RS 4
array 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 296 der Datei TSI_Role\&.php\&.
.SS "getName ()"

.PP
\fBRückgabe:\fP
.RS 4
string 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 118 der Datei TSI_Role\&.php\&.
.SS "getPermission (string $permission)"

.PP
\fBParameter:\fP
.RS 4
\fI$permission\fP 
.RE
.PP
\fBRückgabe:\fP
.RS 4
bool 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 191 der Datei TSI_Role\&.php\&.
.SS "getPermissions ()"

.PP
\fBRückgabe:\fP
.RS 4
array 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 220 der Datei TSI_Role\&.php\&.
.SS "getPermissionsList ()"

.PP
\fBRückgabe:\fP
.RS 4
array 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 227 der Datei TSI_Role\&.php\&.
.SS "getTSIPermission (string $permission)"

.PP
\fBParameter:\fP
.RS 4
\fI$permission\fP 
.RE
.PP
\fBRückgabe:\fP
.RS 4
bool 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 407 der Datei TSI_Role\&.php\&.
.SS "getTSIPermissions ()"

.PP
\fBRückgabe:\fP
.RS 4
array 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 440 der Datei TSI_Role\&.php\&.
.SS "getTSIPermissionsList ()"

.PP
\fBRückgabe:\fP
.RS 4
array 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 447 der Datei TSI_Role\&.php\&.
.SS "setChannelModify (string $permission, bool $granted = \fCfalse\fP)"

.PP
\fBParameter:\fP
.RS 4
\fI$permission\fP 
.br
\fI$granted\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 323 der Datei TSI_Role\&.php\&.
.SS "setChannelModifys (array $channel_modify)"

.PP
\fBParameter:\fP
.RS 4
\fI$channel_modify\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 315 der Datei TSI_Role\&.php\&.
.SS "setIcon (string $icon)"

.PP
\fBParameter:\fP
.RS 4
\fI$icon\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 145 der Datei TSI_Role\&.php\&.
.SS "setID (int $id)"

.PP
\fBParameter:\fP
.RS 4
\fI$id\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 86 der Datei TSI_Role\&.php\&.
.SS "setLevel (int $level)"

.PP
\fBParameter:\fP
.RS 4
\fI$level\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 125 der Datei TSI_Role\&.php\&.
.SS "setModify (string $permission, bool $granted = \fCfalse\fP)"

.PP
\fBParameter:\fP
.RS 4
\fI$permission\fP 
.br
\fI$granted\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 252 der Datei TSI_Role\&.php\&.
.SS "setModifys (array $modify)"

.PP
\fBParameter:\fP
.RS 4
\fI$modify\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 244 der Datei TSI_Role\&.php\&.
.SS "setName (string $name)"

.PP
\fBParameter:\fP
.RS 4
\fI$name\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 105 der Datei TSI_Role\&.php\&.
.SS "setPermission (string $permission, bool $granted = \fCfalse\fP)"

.PP
\fBParameter:\fP
.RS 4
\fI$permission\fP 
.br
\fI$granted\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 167 der Datei TSI_Role\&.php\&.
.SS "setPermissions (array $permissions)"

.PP
\fBParameter:\fP
.RS 4
\fI$permissions\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 159 der Datei TSI_Role\&.php\&.
.SS "setTSIPermission (string $permission, bool $granted = \fCfalse\fP)"

.PP
\fBParameter:\fP
.RS 4
\fI$permission\fP 
.br
\fI$granted\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 387 der Datei TSI_Role\&.php\&.
.SS "setTSIPermissions (array $tsi_permissions)"

.PP
\fBParameter:\fP
.RS 4
\fI$tsi_permissions\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Role_Interface\fP\&.
.PP
Definiert in Zeile 433 der Datei TSI_Role\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
