.TH "TSI_Instance" 3 "Die Okt 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TSI_Instance
.SH SYNOPSIS
.br
.PP
.PP
Abgeleitet von \fBTSI_Instance_Interface\fP\&.
.SS "Öffentliche Methoden"

.in +1c
.ti -1c
.RI "\fBsetID\fP (int $user_id)"
.br
.ti -1c
.RI "\fBgetID\fP ()"
.br
.ti -1c
.RI "\fBsetIP\fP (string $server_ip)"
.br
.ti -1c
.RI "\fBgetIP\fP ()"
.br
.ti -1c
.RI "\fBsetQueryPort\fP (int $query_port)"
.br
.ti -1c
.RI "\fBgetQueryPort\fP ()"
.br
.ti -1c
.RI "\fBsetServerAdmin\fP (string $serveradmin)"
.br
.ti -1c
.RI "\fBgetServerAdmin\fP ()"
.br
.ti -1c
.RI "\fBsetLastPermImport\fP (string $last_perm_import)"
.br
.ti -1c
.RI "\fBgetLastPermImport\fP ()"
.br
.in -1c
.SH "Ausführliche Beschreibung"
.PP 
Definiert in Zeile 32 der Datei TSI_Instance\&.php\&.
.SH "Dokumentation der Elementfunktionen"
.PP 
.SS "getID ()"

.PP
\fBRückgabe:\fP
.RS 4
int 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 73 der Datei TSI_Instance\&.php\&.
.SS "getIP ()"

.PP
\fBRückgabe:\fP
.RS 4
string 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 93 der Datei TSI_Instance\&.php\&.
.SS "getLastPermImport ()"

.PP
\fBRückgabe:\fP
.RS 4
string 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 135 der Datei TSI_Instance\&.php\&.
.SS "getQueryPort ()"

.PP
\fBRückgabe:\fP
.RS 4
int 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 107 der Datei TSI_Instance\&.php\&.
.SS "getServerAdmin ()"

.PP
\fBRückgabe:\fP
.RS 4
string 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 121 der Datei TSI_Instance\&.php\&.
.SS "setID (int $user_id)"

.PP
\fBParameter:\fP
.RS 4
\fI$user_id\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 66 der Datei TSI_Instance\&.php\&.
.SS "setIP (string $server_ip)"

.PP
\fBParameter:\fP
.RS 4
\fI$server_ip\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 80 der Datei TSI_Instance\&.php\&.
.SS "setLastPermImport (string $last_perm_import)"

.PP
\fBParameter:\fP
.RS 4
\fI$last_perm_import\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 128 der Datei TSI_Instance\&.php\&.
.SS "setQueryPort (int $query_port)"

.PP
\fBParameter:\fP
.RS 4
\fI$query_port\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 100 der Datei TSI_Instance\&.php\&.
.SS "setServerAdmin (string $serveradmin)"

.PP
\fBParameter:\fP
.RS 4
\fI$serveradmin\fP 
.RE
.PP

.PP
Implementiert \fBTSI_Instance_Interface\fP\&.
.PP
Definiert in Zeile 114 der Datei TSI_Instance\&.php\&.

.SH "Autor"
.PP 
Automatisch erzeugt von Doxygen für TeamSpeak Interface Client aus dem Quellcode\&.
