.TH "src/TSI_Client_Base.php" 3 "Tue Oct 2 2018" "Version 1.0.4 Beta" "TeamSpeak Interface Client" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/TSI_Client_Base.php
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTSI_Client_Base\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTSI_Client\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for TeamSpeak Interface Client from the source code\&.
